Algoritmo "MÚLTIPLODE10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/10/2024
Var
I : inteiro

Inicio
para i de 1 ate 100 faca
    se ( i % 10 = 0) entao
    escreval(i, " É MÚLTIPLO DE 10")
senao
    escreval(i)
    fimSe
fimPara


Fimalgoritmo