Algoritmo "recepção"

Var
nome, email : caractere
idade : inteiro

Inicio
escreval("Boa tarde! Digite o seu nome: ")
leia(nome)
limpaTela()

escreval("Digite a sua idade: ")
leia(idade)
limpaTela()

escreval("Digite seu email: ")
leia(email)
limpaTela()

escreval("Cadatro efetuado com sucesso!")
escreval("*****************")
escreval("Usuario: ",nome)
escreval("Idade : ",idade)
escreval("Email : ",email)
escreval("******************")

Fimalgoritmo