Algoritmo "SOMATOTAL"

Var
numero1, numero2, numero3, numero4, soma : real

Inicio
escreval("Soma de 4 números")
   escreval("Digite o primeiro número: ")
   leia(numero1)

   escreval("Digite o segundo número: ")
   leia(numero2)

   escreval("Digite o terceiro número: ")
   leia(numero3)

   escreval("Digite o quarto número: ")
   leia(numero4)

   soma <-numero1 + numero2 + numero3 + numero4
   escreval("A soma total dos quatro números é: ",soma)

Fimalgoritmo